version: '3.8'

services:
  private-engine:
    build: .
    container_name: cert-engine-private
    shm_size: '2gb'  # 공유 메모리를 2GB로 늘려줍니다. (핵심!)
    ports:
      - "8000:8010" # 밖에서 8000으로 들어오면 안의 8010으로 연결
    volumes:
      - .:/app:Z
     # - ./private-cert-crawl/configs:/app/configs:Z
    env_file:
      - .env
    command: python run_once.py

  public-engine:
    build: .
    container_name: cert-engine-public
    shm_size: '2gb'  # 공유 메모리를 2GB로 늘려줍니다. (핵심!)
    ports:
      - "8001:8010" # 밖에서 8001으로 들어오면 안의 8010으로 연결
    volumes:
      - .:/app:Z
      - ../cert_data:/cert_data:Z 
    env_file:
      - .env
    command: python -m public_cert_api.run_public --root /cert_data --jmcd ${JMCD} --mode http
    environment:
      - PYTHONPATH=/app # 이게 핵심입니다! 이 한 줄이 있으면 -m 없이도 경로를 잘 찾습니다.

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:Z
    ports:
      - "9090:9090" # 프로메테우스 웹 UI 접속용
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000" # 그라파나 대시보드 접속용
    restart: always
