version: '3.8'

services:
  private-engine:
    build: .
    container_name: cert-engine-private
    shm_size: '2gb'  # 공유 메모리를 2GB로 늘려줍니다. (핵심!)
    volumes:
      - .:/app:Z
      - ./private-cert-crawl/configs:/app/configs:Z
    env_file:
      - .env
    command: python run_once.py 

  public-engine:
    build: .
    container_name: cert-engine-public
    shm_size: '2gb'  # 공유 메모리를 2GB로 늘려줍니다. (핵심!)
    volumes:
      - .:/app:Z
      - ../cert_data:/cert_data:Z 
    env_file:
      - .env
    command: python public_cert_api/run_public.py
