# 1. 전역 설정 (Global)
global:
  scrape_interval: 15s     # 15초마다 데이터를 수집합니다. (너무 자주 하면 서버에 부하가 가요)
  evaluation_interval: 15s # 규칙(알람 등)을 검사하는 주기입니다.

# 2. 수집 대상 설정 (Scrape Configs)
scrape_configs:
  # (1) 프로메테우스 자기 자신을 감시
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']
